//! 8-or-better / A-5 lowball lookup tables.
//!
//! Generated by `scripts/02-lookup_tables` with the A-5 ranking
//! semantics (no straights, no flushes, A-2-3-4-5 = wheel = nuts).
//! Pure data — the runtime evaluator lives in `phe-eight-low`.
#![allow(missing_docs)]

pub mod constants;
pub mod lookup;
pub mod offsets;
