//! 2-7 lowball lookup tables (5-card only).
//!
//! Generated by `phe-scripts gen-deuce-seven-lookup` using
//! `WheelMode::NoPair`. See that binary's docs for the design rationale,
//! including why 6/7-card support is excluded.

pub mod lookup;

pub use lookup::{LOOKUP, LOOKUP_FLUSH};
