//! Hold'em high lookup tables.
//!
//! Generated by `scripts/02-lookup_tables` with `WheelMode::StraightAndFlush`.
//! Verbatim copy of the data from b-inary/holdem-hand-evaluator (MIT).

pub mod heads_up;
pub mod lookup;

pub use heads_up::HEADS_UP_WIN_FREQUENCY;
pub use lookup::{LOOKUP, LOOKUP_FLUSH};
